//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS.WEB.Resources.Models.ViewModels {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateAssignmentViewModel {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateAssignmentViewModel() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ASS.WEB.Resources.Models.ViewModels.CreateAssignmentViewModel", typeof(CreateAssignmentViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AssignmentName {
            get {
                return ResourceManager.GetString("AssignmentName", resourceCulture);
            }
        }
        
        public static string CourseIdsName {
            get {
                return ResourceManager.GetString("CourseIdsName", resourceCulture);
            }
        }
        
        public static string CourseIdsRequired {
            get {
                return ResourceManager.GetString("CourseIdsRequired", resourceCulture);
            }
        }
        
        public static string DescriptionName {
            get {
                return ResourceManager.GetString("DescriptionName", resourceCulture);
            }
        }
        
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        public static string DescriptionTemplate {
            get {
                return ResourceManager.GetString("DescriptionTemplate", resourceCulture);
            }
        }
        
        public static string EndDateName {
            get {
                return ResourceManager.GetString("EndDateName", resourceCulture);
            }
        }
        
        public static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        public static string StartDateName {
            get {
                return ResourceManager.GetString("StartDateName", resourceCulture);
            }
        }
        
        public static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
    }
}
